INSERT INTO cards_data (card_id, card_name, bank_name, card_type) VALUES
(1, 'U.S. Green', 'U.S. Bank', 'credit'),
(2, 'Wells Access Debit', 'Wells Fargo', 'debit'),
(3, 'Chase Travel Rewards', 'Chase', 'credit'),
(4, 'Bank Double Cash', 'Bank of America', 'credit'),
(5, 'TD Everyday Checking', 'TD Bank', 'debit'),
(6, 'Citi Access Debit', 'Citi', 'debit'),
(7, 'Bank Select', 'Bank of America', 'credit'),
(8, 'TD Cashback Debit', 'TD Bank', 'debit'),
(9, 'Discover Student Debit', 'Discover', 'debit'),
(10, 'HSBC Advantage Debit', 'HSBC', 'debit'),
(11, 'U.S. Basic Debit', 'U.S. Bank', 'debit'),
(12, 'U.S. Freedom', 'U.S. Bank', 'credit'),
(13, 'PNC Cashback Debit', 'PNC', 'debit'),
(14, 'American Basic Debit', 'American Express', 'debit'),
(15, 'Capital Gold', 'Capital One', 'credit'),
(16, 'PNC Access Debit', 'PNC', 'debit'),
(17, 'PNC Cash Rewards', 'PNC', 'credit'),
(18, 'TD 360 Debit', 'TD Bank', 'debit'),
(19, 'Capital Simple Debit', 'Capital One', 'debit'),
(20, 'Capital Basic Debit', 'Capital One', 'debit'),
(21, 'Bank Cash Rewards', 'Bank of America', 'credit'),
(22, 'HSBC Student Debit', 'HSBC', 'debit'),
(23, 'U.S. Premier', 'U.S. Bank', 'credit'),
(24, 'Chase 360 Debit', 'Chase', 'debit'),
(25, 'American Everyday Checking', 'American Express', 'debit'),
(26, 'TD Secure Debit', 'TD Bank', 'debit'),
(27, 'Bank Student Debit', 'Bank of America', 'debit'),
(28, 'Bank Basic Debit', 'Bank of America', 'debit'),
(29, 'Citi Premier', 'Citi', 'credit'),
(30, 'Ally Everyday Checking', 'Ally Bank', 'debit'),
(31, 'Discover Select', 'Discover', 'credit'),
(32, 'Barclays Basic Debit', 'Barclays', 'debit'),
(33, 'HSBC Cash Rewards', 'HSBC', 'credit'),
(34, 'Citi Everyday Checking', 'Citi', 'debit'),
(35, 'Synchrony Secure Debit', 'Synchrony', 'debit'),
(36, 'Bank Cashback Debit', 'Bank of America', 'debit'),
(37, 'Wells Advantage Debit', 'Wells Fargo', 'debit'),
(38, 'TD Signature', 'TD Bank', 'credit'),
(39, 'Barclays Serve Card', 'Barclays', 'debit'),
(40, 'Wells Everyday Checking', 'Wells Fargo', 'debit'),
(41, 'Capital Unlimited', 'Capital One', 'credit'),
(42, 'Barclays Venture', 'Barclays', 'credit'),
(43, 'U.S. Savor', 'U.S. Bank', 'credit'),
(44, 'Wells It Cash Back', 'Wells Fargo', 'credit'),
(45, 'Discover Everyday', 'Discover', 'credit'),
(46, 'TD Basic Debit', 'TD Bank', 'debit'),
(47, 'Discover It Cash Back', 'Discover', 'credit'),
(48, 'Capital Select', 'Capital One', 'credit'),
(49, 'Synchrony 360 Debit', 'Synchrony', 'debit'),
(50, 'Barclays Access Debit', 'Barclays', 'debit'),
(51, 'Citi Freedom', 'Citi', 'credit'),
(52, 'HSBC Simple Debit', 'HSBC', 'debit'),
(53, 'American Signature', 'American Express', 'credit'),
(54, 'Citi Cashback Debit', 'Citi', 'debit'),
(55, 'Capital Cash Rewards', 'Capital One', 'credit'),
(56, 'Ally Cashback Debit', 'Ally Bank', 'debit'),
(57, 'Synchrony Basic Debit', 'Synchrony', 'debit'),
(58, 'PNC 360 Debit', 'PNC', 'debit'),
(59, 'American Select', 'American Express', 'credit'),
(60, 'Discover Simple Debit', 'Discover', 'debit'),
(61, 'Barclays Chrome', 'Barclays', 'credit'),
(62, 'Chase Basic Debit', 'Chase', 'debit'),
(63, 'Chase Savor', 'Chase', 'credit'),
(64, 'Citi Travel Rewards', 'Citi', 'credit'),
(65, 'Capital Freedom', 'Capital One', 'credit'),
(66, 'HSBC Unlimited', 'HSBC', 'credit'),
(67, 'Synchrony Advantage Debit', 'Synchrony', 'debit'),
(68, 'HSBC Secure Debit', 'HSBC', 'debit'),
(69, 'Ally 360 Debit', 'Ally Bank', 'debit'),
(70, 'TD It Cash Back', 'TD Bank', 'credit'),
(71, 'Ally Secure Debit', 'Ally Bank', 'debit'),
(72, 'Capital Venture', 'Capital One', 'credit'),
(73, 'Discover Secure Debit', 'Discover', 'debit'),
(74, 'U.S. Simple Debit', 'U.S. Bank', 'debit'),
(75, 'PNC Advantage Debit', 'PNC', 'debit'),
(76, 'American Student Debit', 'American Express', 'debit'),
(77, 'Wells Basic Debit', 'Wells Fargo', 'debit'),
(78, 'Citi Venture', 'Citi', 'credit'),
(79, 'PNC Serve Card', 'PNC', 'debit'),
(80, 'PNC Everyday Checking', 'PNC', 'debit'),
(81, 'Citi Serve Card', 'Citi', 'debit'),
(82, 'HSBC Platinum', 'HSBC', 'credit'),
(83, 'Chase Select', 'Chase', 'credit'),
(84, 'Citi Chrome', 'Citi', 'credit'),
(85, 'Synchrony Chrome', 'Synchrony', 'credit'),
(86, 'TD Student Debit', 'TD Bank', 'debit'),
(87, 'American Savor', 'American Express', 'credit'),
(88, 'Citi It Cash Back', 'Citi', 'credit'),
(89, 'HSBC It Cash Back', 'HSBC', 'credit'),
(90, 'Synchrony It Cash Back', 'Synchrony', 'credit'),
(91, 'Capital Secure Debit', 'Capital One', 'debit'),
(92, 'Wells Savor', 'Wells Fargo', 'credit'),
(93, 'Capital Premier', 'Capital One', 'credit'),
(94, 'American Advantage Debit', 'American Express', 'debit'),
(95, 'TD Chrome', 'TD Bank', 'credit'),
(96, 'Ally Venture', 'Ally Bank', 'credit'),
(97, 'Barclays Preferred', 'Barclays', 'credit'),
(98, 'Ally Access Debit', 'Ally Bank', 'debit'),
(99, 'U.S. Preferred', 'U.S. Bank', 'credit'),
(100, 'Synchrony Student Debit', 'Synchrony', 'debit'),
(101, 'HSBC Double Cash', 'HSBC', 'credit'),
(102, 'Ally Chrome', 'Ally Bank', 'credit'),
(103, 'American Premier', 'American Express', 'credit'),
(104, 'Synchrony Venture', 'Synchrony', 'credit'),
(105, 'American Secure Debit', 'American Express', 'debit'),
(106, 'Wells Chrome', 'Wells Fargo', 'credit'),
(107, 'American Serve Card', 'American Express', 'debit'),
(108, 'Wells Signature', 'Wells Fargo', 'credit'),
(109, 'TD Access Debit', 'TD Bank', 'debit'),
(110, 'Citi Simple Debit', 'Citi', 'debit'),
(111, 'U.S. Access Debit', 'U.S. Bank', 'debit'),
(112, 'Wells Select', 'Wells Fargo', 'credit'),
(113, 'PNC Preferred', 'PNC', 'credit'),
(114, 'Barclays Secure Debit', 'Barclays', 'debit'),
(115, 'Synchrony Freedom', 'Synchrony', 'credit'),
(116, 'U.S. Secure Debit', 'U.S. Bank', 'debit'),
(117, 'Discover Travel Rewards', 'Discover', 'credit'),
(118, 'Ally Unlimited', 'Ally Bank', 'credit');